{% set version = "0.3.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-wesanderson
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/wesanderson_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/wesanderson/wesanderson_{{ version }}.tar.gz
  sha256: c92e5604e1e149e00f49fd236c6ab8cd09d96106eb14479f7839e6996bf95e4e

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('wesanderson')"           # [not win]
    - "\"%R%\" -e \"library('wesanderson')\""  # [win]

about:
  home: https://github.com/karthik/wesanderson
  license: MIT
  summary: Palettes generated mostly from 'Wes Anderson' movies.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: wesanderson
# Title: A Wes Anderson Palette Generator
# Description: Palettes generated mostly from 'Wes Anderson' movies.
# Date: 2018-03-29
# Version: 0.3.6
# Authors@R: c(person("Karthik", "Ram", role = c("aut", "cre"), email = "karthik.ram@gmail.com", comment = c(ORCID = "0000-0002-0233-1757")), person("Hadley", "Wickham", role = "aut", email = "h.wickham@gmail.com"), person("Clark", "Richards", role = "ctb", email = "crichards@whoi.edu"), person("Aaron", "Baggett", role = "ctb", email = "aaronbaggett@gmail.com"))
# Depends: R (>= 3.0)
# License: MIT + file LICENSE
# LazyData: true
# Suggests: ggplot2
# URL: https://github.com/karthik/wesanderson
# BugReports: https://github.com/karthik/wesanderson/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-04-19 23:13:48 UTC; karthik
# Author: Karthik Ram [aut, cre] (<https://orcid.org/0000-0002-0233-1757>), Hadley Wickham [aut], Clark Richards [ctb], Aaron Baggett [ctb]
# Maintainer: Karthik Ram <karthik.ram@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-04-20 04:11:42 UTC
